### PR TITLE
Tab bar

### PR DESCRIPTION
**Pull request by NoahHines**
Cell nibs are now connected to the root tab view controller. Next we can add labels and dummy data.

### CODE REVIEW

**Comment by cnmcgrath** [comment]
For announcements, schedule, and prizes cells, you have a few warnings about IB constraints. Please fix the auto layout issues by either accepting the suggestions or forcing new layout constraints. Once that's taken care of I'll +1 it. 

Other than that looks good.

**Comment by NoahHines** [comment]
Good find. Fixing now.

**Comment by NoahHines** [comment]
Review please.

**Comment by cnmcgrath** [comment]
+1

**Pull request merged**
